/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.atividade_04_uc15.gui;

import static br.com.senac.atividade_04_uc15.gui.CadastrarFuncionarios.convertLocalDate;
import br.com.senac.atividade_04_uc15.persistencia.CatalogoProduto;
import br.com.senac.atividade_04_uc15.persistencia.CatalogoProdutoDAO;
import java.text.NumberFormat;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcelo
 */
public class CadastrarProdutos extends javax.swing.JFrame {

    private static final DateTimeFormatter FORMATO_BR = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    /**
     * Creates new form PesquisarProdutos
     */
    public CadastrarProdutos() {
        initComponents();
    }

    private void limparCampos() {
        txtTitulo.setText("");
        txtDescricao.setText("");
        txtValor.setText("");
        txtCodigoBarras.setText("");
        txtData.setText("");
        txtQuantidade.setText("");
        cmbCondicao.setSelectedIndex(0);
        cmbTipo.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTituloInicial = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtValor = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        lblDescricao = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        cmbCondicao = new javax.swing.JComboBox<>();
        lblCondicao = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        lblData1 = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        btnPesquisar2 = new javax.swing.JButton();
        btnCadastrarProduto = new javax.swing.JButton();
        btnListarProdutos = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Produtos | SGLO");

        jPanel1.setBackground(new java.awt.Color(231, 234, 239));

        jPanel2.setBackground(new java.awt.Color(189, 194, 213));

        lblTituloInicial.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTituloInicial.setForeground(new java.awt.Color(51, 51, 51));
        lblTituloInicial.setText("Cadastrar Produtos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(lblTituloInicial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTituloInicial)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(231, 234, 239));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setToolTipText("");

        txtValor.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtValor.setToolTipText("Especifique o valor unitário do produto.");
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("Título do Produto");

        txtDescricao.setColumns(20);
        txtDescricao.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtDescricao.setRows(5);
        txtDescricao.setToolTipText("Descreva as características do produto.");
        jScrollPane1.setViewportView(txtDescricao);

        lblDescricao.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(51, 51, 51));
        lblDescricao.setText("Descrição");

        txtTitulo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtTitulo.setToolTipText("Digite o título do produto.");
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        lblValor.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblValor.setForeground(new java.awt.Color(51, 51, 51));
        lblValor.setText("Valor Unitário");

        txtQuantidade.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtQuantidade.setToolTipText("Informe a quantidade do produto.");
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        lblQuantidade.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblQuantidade.setForeground(new java.awt.Color(51, 51, 51));
        lblQuantidade.setText("Quantidade");

        lblTipo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(51, 51, 51));
        lblTipo.setText("Tipo de Produto");

        cmbTipo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- ESCOLHA - ", " Disco de Vinil", " CD - Compact Disc", " Artigos de Papelaria", " Livros", " Moda e Vestuário", " Equipamentos Eletrônicos", " Instrumentos Musicais", " Raridades" }));
        cmbTipo.setToolTipText("Escolha o tipo de produto.");

        cmbCondicao.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cmbCondicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- ESCOLHA - ", " Produto Novo", " Usado (Ótimo)", " Usado (Bom)", " Usado (Marcas de Uso)" }));
        cmbCondicao.setToolTipText("Escolha a condição do produto.");

        lblCondicao.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblCondicao.setForeground(new java.awt.Color(51, 51, 51));
        lblCondicao.setText("Condição");

        lblData.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblData.setForeground(new java.awt.Color(51, 51, 51));
        lblData.setText("Data de Inclusão");

        txtData.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtData.setToolTipText("Digite a data de inclusão do produto.");
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        lblData1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblData1.setForeground(new java.awt.Color(51, 51, 51));
        lblData1.setText("Código de Barras");

        txtCodigoBarras.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCodigoBarras.setToolTipText("Digite a data de inclusão do produto.");
        txtCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBarrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescricao))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblValor)
                                .addComponent(txtValor)
                                .addComponent(lblQuantidade)
                                .addComponent(txtQuantidade)
                                .addComponent(lblTipo)
                                .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCondicao)
                                .addComponent(cmbCondicao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblData)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblData1)
                            .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(lblValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCondicao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblData1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnPesquisar2.setBackground(new java.awt.Color(197, 202, 222));
        btnPesquisar2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnPesquisar2.setForeground(new java.awt.Color(51, 51, 51));
        btnPesquisar2.setText("Sair");
        btnPesquisar2.setToolTipText("Clique para voltar à tela anterior");
        btnPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar2ActionPerformed(evt);
            }
        });

        btnCadastrarProduto.setBackground(new java.awt.Color(197, 202, 222));
        btnCadastrarProduto.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCadastrarProduto.setForeground(new java.awt.Color(51, 51, 51));
        btnCadastrarProduto.setText("Cadastrar");
        btnCadastrarProduto.setToolTipText("Clique para cadastrar novo produto.");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        btnListarProdutos.setBackground(new java.awt.Color(197, 202, 222));
        btnListarProdutos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnListarProdutos.setForeground(new java.awt.Color(51, 51, 51));
        btnListarProdutos.setText("Listar Produtos");
        btnListarProdutos.setToolTipText("Clique para listar os produtos em estoque.");
        btnListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProdutosActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(197, 202, 222));
        btnLimpar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(51, 51, 51));
        btnLimpar.setText("Limpar Campos");
        btnLimpar.setToolTipText("Clique para listar os produtos em estoque.");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnPesquisar2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void btnPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnPesquisar2ActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void btnListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProdutosActionPerformed
        // TODO add your handling code here:
        PesquisarProdutos pesquisarProdutos = new PesquisarProdutos();
        pesquisarProdutos.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListarProdutosActionPerformed

    private void txtCodigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBarrasActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        // TODO add your handling code here:

        String strTitulo = txtTitulo.getText();
        String strDescricao = txtDescricao.getText();
        String strDataInclusao = txtData.getText();
        String strValorUnitario = txtValor.getText();
        String strQuantidade = txtQuantidade.getText();
        int strTipo = cmbTipo.getSelectedIndex();
        int strCondicao = cmbCondicao.getSelectedIndex();
        String strCodigo = txtCodigoBarras.getText();

        if (strTitulo.isEmpty() || strDescricao.isEmpty() || strDataInclusao.isEmpty() || strValorUnitario.isEmpty() || strQuantidade.isEmpty() || strTipo == 0 || strCondicao == 0 || strCodigo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos. ");
        } else {
            //Teste de validação de entrada de Data:
            String strTesteData = txtData.getText();
            boolean testeData = strTesteData.matches("^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/(\\d{4})$");

            //Teste de validação de entrada de código de barras:
            String strTesteCodigo = txtCodigoBarras.getText();
            boolean testeCodigo = strTesteCodigo.matches("[0-9]{6}");

            //Teste de validação de entrada de valores:
            String strTesteValorUnitario = txtValor.getText();
            boolean testeValor = strTesteValorUnitario.matches("\\d+(\\.\\d{1,2})?");

            //Teste de validação de entrada de quantidade:
            String strTesteQuantidade = txtQuantidade.getText();
            boolean testeQuantidade = strTesteQuantidade.matches("\\d+");

            if (testeCodigo == true && testeData == true && testeValor == true && testeQuantidade == true) {
                CatalogoProduto p = new CatalogoProduto();
                p.setCodProduto(txtCodigoBarras.getText());
                p.setTitulo(txtTitulo.getText());
                p.setValor(Double.parseDouble(txtValor.getText()));
                p.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
                p.setEntrada(convertLocalDate(txtData.getText()));
                p.setIdTipo(cmbTipo.getSelectedIndex());
                p.setIdCondicao(cmbCondicao.getSelectedIndex());
                p.setDescricao(txtDescricao.getText());

                CatalogoProdutoDAO catalogoDAO = new CatalogoProdutoDAO();
                catalogoDAO.Cadastrar(p);
                JOptionPane.showMessageDialog(null, "Cadastro de novo produto realizado com sucesso! \n");

                limparCampos();

            } else {
                JOptionPane.showMessageDialog(null, "As datas devem seguir o formato dd/mm/aaaa. \n" + "O código deverá ter sequencia numérica de 6 dígitos. \n" + "A quantidade mínima será 1. \n" + "Os valores deverão estar em x.xx com valor mínimo de 0.01. \n " + "Os campos de escolha deverão ser selecionados. \n");
            }

        }


    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListarProdutos;
    private javax.swing.JButton btnPesquisar2;
    private javax.swing.JComboBox<String> cmbCondicao;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCondicao;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloInicial;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
