/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.atividade_04_uc15.gui;

import br.com.senac.atividade_04_uc15.Compras;
import br.com.senac.atividade_04_uc15.ListaCompras;
import br.com.senac.atividade_04_uc15.persistencia.CatalogoProduto;
import br.com.senac.atividade_04_uc15.persistencia.CatalogoProdutoDAO;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcelo
 */
public class PainelVendas extends javax.swing.JFrame {

    /**
     * Creates new form PainelPesquisaFixa
     */
    public PainelVendas() {
        initComponents();
        limparCampos();
        atualizarValorTotal();
        atualizarTabela();
    }

    public void limparCampos() {
        txtCodigoProduto.setText("");
        txtQtdEstoque.setText("");
        txtQtdListaCompras.setText("");
        txtDescricao.setText("");
        txtCodigoProdutoLista.setText("");

    }

    private Double vlrTotal;

    private void valorTotal(String valor) {
        this.vlrTotal = 0.0;
        if (valor != null && !valor.isEmpty()) {
            this.vlrTotal = Double.parseDouble(valor);
        } else {
            this.vlrTotal = 0.0;
        }
    }

    public void atualizarValorTotal() {
        valorTotal(ListaCompras.getValorTotal());

        NumberFormat formatoMoeda = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        double valor = vlrTotal;
        txtValor.setText(formatoMoeda.format(valor));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTituloInicial = new javax.swing.JLabel();
        lblTituloInicialTop = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtCodigoProduto = new javax.swing.JTextField();
        txtQtdEstoque = new javax.swing.JTextField();
        lblCodigoProduto = new javax.swing.JLabel();
        txtQtdListaCompras = new javax.swing.JTextField();
        lblQtdEstoque = new javax.swing.JLabel();
        lblQtdListaCompras = new javax.swing.JLabel();
        btnIncluir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnListarClientes = new javax.swing.JButton();
        btnCadastrarClientes = new javax.swing.JButton();
        btnPesquisarProdutos = new javax.swing.JButton();
        btnListarVendas = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigoProdutoLista = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaCompras = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnAlterarQtd = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnAvancar = new javax.swing.JButton();
        txtValor = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Painel de Vendas - Loja Orion");

        jPanel1.setBackground(new java.awt.Color(230, 233, 238));

        jPanel2.setBackground(new java.awt.Color(189, 194, 213));

        lblTituloInicial.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTituloInicial.setForeground(new java.awt.Color(51, 51, 51));
        lblTituloInicial.setText("Sistema Integrado de  Gestão de Loja");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTituloInicial)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTituloInicial)
                    .addGap(0, 39, Short.MAX_VALUE)))
        );

        lblTituloInicialTop.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        lblTituloInicialTop.setForeground(new java.awt.Color(51, 51, 51));
        lblTituloInicialTop.setText("Controle de Vendas");

        jPanel3.setBackground(new java.awt.Color(230, 233, 238));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(288, 339));

        txtCodigoProduto.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoProduto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCodigoProduto.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigoProduto.setToolTipText("Insira o código do produto para incluir na lista.");
        txtCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProdutoActionPerformed(evt);
            }
        });

        txtQtdEstoque.setBackground(new java.awt.Color(255, 255, 255));
        txtQtdEstoque.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtQtdEstoque.setForeground(new java.awt.Color(0, 0, 0));
        txtQtdEstoque.setToolTipText("Digite a quantidade do produto.");
        txtQtdEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdEstoqueActionPerformed(evt);
            }
        });

        lblCodigoProduto.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblCodigoProduto.setForeground(new java.awt.Color(51, 51, 51));
        lblCodigoProduto.setText("Cód.Produto");

        txtQtdListaCompras.setBackground(new java.awt.Color(255, 255, 255));
        txtQtdListaCompras.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtQtdListaCompras.setForeground(new java.awt.Color(0, 0, 0));
        txtQtdListaCompras.setToolTipText("Valor unitário do produto.");
        txtQtdListaCompras.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtQtdListaCompras.setEnabled(false);
        txtQtdListaCompras.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtQtdListaCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdListaComprasActionPerformed(evt);
            }
        });

        lblQtdEstoque.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblQtdEstoque.setForeground(new java.awt.Color(51, 51, 51));
        lblQtdEstoque.setText("Quantidade");

        lblQtdListaCompras.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblQtdListaCompras.setForeground(new java.awt.Color(51, 51, 51));
        lblQtdListaCompras.setText("Ítens na lista de compras");

        btnIncluir.setBackground(new java.awt.Color(197, 202, 222));
        btnIncluir.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnIncluir.setForeground(new java.awt.Color(51, 51, 51));
        btnIncluir.setText("Incluir");
        btnIncluir.setToolTipText("Clique para incluir o ítem à lista.");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdListaCompras)
                    .addComponent(txtQtdListaCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdEstoque)
                    .addComponent(txtQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoProduto)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblCodigoProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQtdEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQtdListaCompras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQtdListaCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel4.setBackground(new java.awt.Color(230, 233, 238));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSair.setBackground(new java.awt.Color(197, 202, 222));
        btnSair.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnSair.setForeground(new java.awt.Color(51, 51, 51));
        btnSair.setText("Sair");
        btnSair.setToolTipText("Clique para retornar à tela inicial.");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnListarClientes.setBackground(new java.awt.Color(197, 202, 222));
        btnListarClientes.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnListarClientes.setForeground(new java.awt.Color(51, 51, 51));
        btnListarClientes.setText("Pesquisar Clientes");
        btnListarClientes.setToolTipText("Clique para listar os clientes cadastrados.");
        btnListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarClientesActionPerformed(evt);
            }
        });

        btnCadastrarClientes.setBackground(new java.awt.Color(197, 202, 222));
        btnCadastrarClientes.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCadastrarClientes.setForeground(new java.awt.Color(51, 51, 51));
        btnCadastrarClientes.setText("Cadastrar Clientes");
        btnCadastrarClientes.setToolTipText("Clique para cadstrar clientes.");
        btnCadastrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClientesActionPerformed(evt);
            }
        });

        btnPesquisarProdutos.setBackground(new java.awt.Color(197, 202, 222));
        btnPesquisarProdutos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnPesquisarProdutos.setForeground(new java.awt.Color(51, 51, 51));
        btnPesquisarProdutos.setText("Pesquisar Produtos");
        btnPesquisarProdutos.setToolTipText("Clique para pesquisar produtos.");
        btnPesquisarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdutosActionPerformed(evt);
            }
        });

        btnListarVendas.setBackground(new java.awt.Color(197, 202, 222));
        btnListarVendas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnListarVendas.setForeground(new java.awt.Color(51, 51, 51));
        btnListarVendas.setText("Listar Itens Vendidos");
        btnListarVendas.setToolTipText("Clique para listar os produtos vendidos.");
        btnListarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarVendasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnListarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(btnListarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel5.setBackground(new java.awt.Color(230, 233, 238));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCodigo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(51, 51, 51));
        lblCodigo.setText("Código");

        txtCodigoProdutoLista.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoProdutoLista.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txtCodigoProdutoLista.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigoProdutoLista.setToolTipText("Digite o código do produto.");
        txtCodigoProdutoLista.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigoProdutoLista.setEnabled(false);
        txtCodigoProdutoLista.setSelectionColor(new java.awt.Color(51, 51, 51));
        txtCodigoProdutoLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProdutoListaActionPerformed(evt);
            }
        });

        lblDescricao.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(51, 51, 51));
        lblDescricao.setText("Descrição");

        txtDescricao.setBackground(new java.awt.Color(255, 255, 255));
        txtDescricao.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(51, 51, 51));
        txtDescricao.setToolTipText("Apresenta a descrição do último produto incluído à lista.");
        txtDescricao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDescricao.setEnabled(false);
        txtDescricao.setSelectionColor(new java.awt.Color(51, 51, 51));
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        tblListaCompras.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        tblListaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblListaCompras.setToolTipText("Lista de Produtos ");
        tblListaCompras.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tblListaCompras);

        btnExcluir.setBackground(new java.awt.Color(197, 202, 222));
        btnExcluir.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(51, 51, 51));
        btnExcluir.setText("Excluir Item");
        btnExcluir.setToolTipText("Clique para excluir um item da lista.");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterarQtd.setBackground(new java.awt.Color(197, 202, 222));
        btnAlterarQtd.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnAlterarQtd.setForeground(new java.awt.Color(51, 51, 51));
        btnAlterarQtd.setText("Alterar Qtd");
        btnAlterarQtd.setToolTipText("Clique para alterar a quantidade de um produto da lista.");
        btnAlterarQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarQtdActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(197, 202, 222));
        btnLimpar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(51, 51, 51));
        btnLimpar.setText("Limpar Lista");
        btnLimpar.setToolTipText("Clique para limpar a lista.");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnAvancar.setBackground(new java.awt.Color(197, 202, 222));
        btnAvancar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnAvancar.setForeground(new java.awt.Color(51, 51, 51));
        btnAvancar.setText("Avançar");
        btnAvancar.setToolTipText("Clique para avançar com a venda.");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        txtValor.setBackground(new java.awt.Color(255, 255, 255));
        txtValor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtValor.setForeground(new java.awt.Color(51, 51, 51));
        txtValor.setToolTipText("Digite o código do produto.");
        txtValor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtValor.setEnabled(false);
        txtValor.setSelectionColor(new java.awt.Color(51, 51, 51));
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(51, 51, 51));
        lblTotal.setText("Valor Total");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTotal)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCodigo)
                                .addComponent(txtCodigoProdutoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDescricao)
                                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnAlterarQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoProdutoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterarQtd)
                    .addComponent(btnLimpar)
                    .addComponent(btnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(570, 570, 570)
                        .addComponent(lblTituloInicialTop)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTituloInicialTop)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProdutoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        TelaInicial telaInicial = new TelaInicial();
        ListaCompras.limparLista();
        telaInicial.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtQtdEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdEstoqueActionPerformed

    private void txtQtdListaComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdListaComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdListaComprasActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:

        String strCodigo = txtCodigoProduto.getText();
        String strQuantidade = txtQtdEstoque.getText();
        Integer verificador;
        verificador = ListaCompras.retornarPosicao(strCodigo);

        if (verificador == -1) {
            if (strCodigo.isEmpty()
                    || strQuantidade.isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo 'código do produto' e o campo 'quantidade' devem ser preenchidos. ");
            } else {
                //Teste de validação de entrada de código do produto:
                String strTesteCodigo = txtCodigoProduto.getText();
                boolean testeCodigo = strTesteCodigo.matches("[0-9]{6}");

                //Teste de validação de entrada de quantidade:
                String strTesteQuantidade = txtQtdEstoque.getText();
                boolean testeQuantidade = strTesteQuantidade.matches("\\d+");

                CatalogoProduto p = new CatalogoProduto();
                CatalogoProdutoDAO catalogoProdutoDAO = new CatalogoProdutoDAO();
                p = catalogoProdutoDAO.buscarPorCodigo(strCodigo);
                int qtd = p.getQuantidade();
                boolean testeEstoque;

                if (qtd < (Integer.parseInt(strQuantidade))) {
                    JOptionPane.showMessageDialog(null, "Não há produtos suficientes no estoque! \n");
                    testeEstoque = false;
                    limparCampos();
                } else {
                    testeEstoque = true;
                }

                if (testeQuantidade == true && testeCodigo == true && testeEstoque == true) {

                    Compras c = new Compras();
                    ListaCompras listaCompras = new ListaCompras();

                    p = catalogoProdutoDAO.buscarPorCodigo(txtCodigoProduto.getText());

                    if (p == null) {
                        JOptionPane.showMessageDialog(null, "Produto não encontrado! \n");
                        limparCampos();

                    } else {

                        String valorTotal;

                        c.setCodigoProduto(p.getCodProduto());
                        c.setTituloProduto(p.getTitulo());
                        c.setValorUnitario(String.valueOf(p.getValor()));
                        c.setQuantidade(txtQtdEstoque.getText());
                        c.setValorTotal(String.valueOf(p.getValor()));

                        listaCompras.adicionar(c);

                        JOptionPane.showMessageDialog(null, "Produto incluido à lista de compras! \n");

                        limparCampos();
                        atualizarTabela();
                        txtCodigoProdutoLista.setText(c.getCodigoProduto());
                        txtDescricao.setText(c.getTituloProduto());
                        txtQtdListaCompras.setText(String.valueOf(tblListaCompras.getRowCount()));
                        atualizarValorTotal();

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "O campo código deverá estar preenchido com 06 dígitos. O campo quantidade deverá ter no mínimo 1 (somente números).");

                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Produto já se encontra na lista, ajuste a quantidade.");
            txtCodigoProduto.setText("");
            txtQtdEstoque.setText("");

        }

    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarClientesActionPerformed
        // TODO add your handling code here:
        PesquisarClientes pesquisarClientes = new PesquisarClientes();
        pesquisarClientes.setVisible(true);

    }//GEN-LAST:event_btnListarClientesActionPerformed

    private void btnCadastrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClientesActionPerformed
        // TODO add your handling code here:
        CadastrarClientes cadastrarClientes = new CadastrarClientes();
        cadastrarClientes.setVisible(true);

    }//GEN-LAST:event_btnCadastrarClientesActionPerformed

    private void btnPesquisarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdutosActionPerformed
        // TODO add your handling code here:
        PesquisarProdutos pesquisarProdutos = new PesquisarProdutos();
        pesquisarProdutos.setVisible(true);
    }//GEN-LAST:event_btnPesquisarProdutosActionPerformed

    private void btnListarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarVendasActionPerformed
        // TODO add your handling code here:
        TelaControleVendas controleVendas = new TelaControleVendas();
        controleVendas.setVisible(true);
    }//GEN-LAST:event_btnListarVendasActionPerformed

    private void txtCodigoProdutoListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProdutoListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProdutoListaActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblListaCompras.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma linha para excluir o produto da lista.");
            return;
        }

        ListaCompras.excluir(linhaSelecionada);
        atualizarValorTotal();

        NumberFormat formatoMoeda = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        double valor = vlrTotal;
        txtValor.setText(formatoMoeda.format(valor));

        atualizarTabela();
        txtQtdListaCompras.setText(String.valueOf(tblListaCompras.getRowCount()));

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        // TODO add your handling code here:
        int numLista = tblListaCompras.getRowCount();

        if (numLista == 0) {
            JOptionPane.showMessageDialog(this, "Não existem produtos na lista.");
        } else {
            ConclusaoVenda conclusao = new ConclusaoVenda();

            conclusao.setVisible(true);
            conclusao.setValorTotal(vlrTotal);

        }

    }//GEN-LAST:event_btnAvancarActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void btnAlterarQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarQtdActionPerformed
        // TODO add your handling code here:       
        AlterarQtd alterarQtd = new AlterarQtd();

        alterarQtd.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                atualizarValorTotal();
                atualizarTabela();
            }
        });

        int testeLinha = tblListaCompras.getSelectedRow();

        if (testeLinha == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma linha para atualizar a quantidade do produto da lista.");
        } else {
            alterarQtd.linha(tblListaCompras.getSelectedRow());

            // Exibe a tela de alteração
            alterarQtd.setVisible(true);
        }


    }//GEN-LAST:event_btnAlterarQtdActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        ListaCompras.limparLista();
        atualizarValorTotal();
        limparCampos();
        atualizarTabela();
        txtQtdListaCompras.setText(String.valueOf(tblListaCompras.getRowCount()));

    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelVendas().setVisible(true);
            }
        });
    }

    public void atualizarTabela() {
        tblListaCompras.setModel(montarTabela());
    }

    private DefaultTableModel montarTabela() {

        String[] colunas = {"Cód.Produto", "Título", "Valor Unitário", "Quantidade", "Sub-Total"};

        DefaultTableModel tabela = new DefaultTableModel(colunas, 0);

        ArrayList<Compras> lista;
        lista = ListaCompras.listar();

        for (int i = 0; i < lista.size(); i++) {

            Compras c = lista.get(i);
            String[] linha = {
                c.getCodigoProduto(),
                c.getTituloProduto(),
                c.getValorUnitario(),
                c.getQuantidade(),
                c.getValorTotal()};

            tabela.addRow(linha);

        }
        atualizarValorTotal();
        return tabela;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarQtd;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnCadastrarClientes;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListarClientes;
    private javax.swing.JButton btnListarVendas;
    private javax.swing.JButton btnPesquisarProdutos;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoProduto;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblQtdEstoque;
    private javax.swing.JLabel lblQtdListaCompras;
    private javax.swing.JLabel lblTituloInicial;
    private javax.swing.JLabel lblTituloInicialTop;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblListaCompras;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtCodigoProdutoLista;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtQtdEstoque;
    private javax.swing.JTextField txtQtdListaCompras;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
